name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        ubuntu-version: [ubuntu-18.04, ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Check versions
        run: |
          python3 --version
