name: Base CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  k8s-job-1:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Interact with the cluster
        run: kubectl get nodes

  k8s-job-2:
    name: Build example and deploy to minikube
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster
      run: kubectl get pods -A
