name: Android / iOS Launch

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:

  android-launch:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: "google_apis"
          arch: "x86_64"
          profile: "Nexus 6"
          avd-name: "Nexus"
          emulator-options: "-no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none"
          script: emulator -list-avds

  ios-launch:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 11'
          os: "iOS"
          os_version: ">=14.0"
      - run: xcrun simctl list | grep Booted